# Generated by Django 5.0.14 on 2026-02-16 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('github_handle', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fenix_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to='fenix.user')),
            ],
            options={
                'db_table': 'fenix_teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_data', models.TextField()),
                ('assistant_type', models.CharField(default='claude-code', max_length=50)),
                ('repo', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('report_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='fenix.user')),
            ],
            options={
                'db_table': 'fenix_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_teams', to='fenix.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sessions', to='fenix.team')),
            ],
            options={
                'db_table': 'fenix_team_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='fenix_team__team_id_70524c_idx'), models.Index(fields=['session'], name='fenix_team__session_bf65db_idx')],
                'unique_together': {('team', 'session')},
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to='fenix.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='fenix.user')),
            ],
            options={
                'db_table': 'fenix_team_users',
                'ordering': ['role', 'created_at'],
                'indexes': [models.Index(fields=['team'], name='fenix_team__team_id_674659_idx'), models.Index(fields=['user'], name='fenix_team__user_id_cffd86_idx')],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner', '-created_at'], name='fenix_sessi_owner_i_06802c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['assistant_type'], name='fenix_sessi_assista_d5c84c_idx'),
        ),
    ]
